"""add line and arrow region types

Revision ID: 4d9765c201a3
Revises: 921b5f9a0743
Create Date: 2026-06-14 13:17:29.245315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9765c201a3'
down_revision: Union[str, None] = '921b5f9a0743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE regiontype ADD VALUE IF NOT EXISTS 'LINE'")
    op.execute("ALTER TYPE regiontype ADD VALUE IF NOT EXISTS 'ARROW'")
    op.execute("ALTER TYPE regioncontenttype ADD VALUE IF NOT EXISTS 'QUESTION_POINT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
