"""add_is_flagged_to_questions

Revision ID: 5fd8a7465503
Revises: b77d840ab41e
Create Date: 2026-06-14 22:37:11.223137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd8a7465503'
down_revision: Union[str, None] = 'b77d840ab41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_questions', sa.Column('is_flagged', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_questions', 'is_flagged')
    # ### end Alembic commands ###
