"""Add attempt limit and support new question types

Revision ID: 921b5f9a0743
Revises: 49a8370ccde4
Create Date: 2026-06-13 19:06:38.666539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921b5f9a0743'
down_revision: Union[str, None] = '49a8370ccde4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('attempt_limit', sa.Integer(), nullable=False))
    
    # Register new enum values in PostgreSQL type questiontype
    op.execute("ALTER TYPE questiontype ADD VALUE IF NOT EXISTS 'single_choice'")
    op.execute("ALTER TYPE questiontype ADD VALUE IF NOT EXISTS 'essay'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'attempt_limit')
    # ### end Alembic commands ###
