"""add hide_grades column

Revision ID: b77d840ab41e
Revises: 23d45ef4512e
Create Date: 2026-06-14 17:58:08.741463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77d840ab41e'
down_revision: Union[str, None] = '23d45ef4512e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hide_grades', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hide_grades')
    # ### end Alembic commands ###
